// AUTO-GENERATED by packages/contracts/scripts/deploy.ts — do not edit.
export const deployedNetwork = "localhost";
export const deployedChainId = 31337;
export const contractAddresses = {
  "AuditLog": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  "PatientRegistry": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  "ConsentManager": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  "MedicalRecordRegistry": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
  "TreatmentRegistry": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
} as const;
